### ISSUE TITLE
Parasite Eve 2: game crashes on fire escape sequence

### ISSUE THREAD

**Issue by ZapBlaze** [Jetup13/PlayStation-Classic-Wiki#1]
when running past the second camera change (where a trigger is) the game freezes. background audio plays as normal, but game stops proceeding. 

It looks like a compatibility option was removed for parasite eve 2 and vandal hearts(?), so maybe that did it?

**Comment by KMFDManic** [comment]
@ZapBlaze That isn't why it crashes, last I checked.  The clock speed (in core options) of the Core has to be at 70 or higher for games like Parasite Eve 2, and select others, which was why I pushed for changes in PCSX for clock speed control, since some games absolutely need 70 to fix the issues.  Compatibility options weren't removed.  They are no longer needed, as they are hard code fixed now.
